### ISSUE TITLE
PinePhone Pro Support

### ISSUE THREAD

**Issue by BraidenPsiuk** [LiveGTech/gShell#20]
The minimum system requirements [here](https://liveg.tech/os/get/) seem to suggest it might be possible to run LiveG OS on a PinePhone Pro, but I tried it with TowBoot and was unable to get it to boot. Is the PinePhone Pro planned to be supported?

**Comment by James-Livesey** [comment]
Hi Braiden! Thanks for checking out LiveG OS, it's really appreciated. The current build at the aforementioned link is only designed to run on desktop 64-bit (amd64) processors (which might seem weird, but that's because the OS also runs on the desktop!). For the PinePhone, there isn't really an official build since I've mainly been relying on Mobian as the main OS for mobile gShell development at the moment — gShell simply runs on top of that as a root X11 window.

That being said, I'd really like to make the PinePhone and PinePhone Pro support LiveG OS properly soon. I don't own a PinePhone Pro (just the regular PinePhone) but I believe that there are only a few minor differences in the PinePhone Pro's architecture compared to the PinePhone's that would need to be considered for an official build to be made. In the meantime, I'd suggest just launching gShell at startup on an existing PinePhone Linux distro (Mobian being the one I have used for development so far and recommend for gShell) to get more-or-less the same experience of what it would be like on an official build.

(Running `startx path/to/gshell` at startup is your friend! I'm happy to help with getting it running on Mobian/other distros, and especially with configuring the [_device description file_](https://docs.liveg.tech/?product=gshell&page=device.md)!)

I should also make it a bit more clear on the website as to where the build can run! Those minimum system requirements should really include the system architecture details...

(Also, I'd recommend playing with LiveG OS on the desktop in a VirtualBox or QEMU VM — it features some cool stuff that's been in-development lately!)

-James.

**Comment by BraidenPsiuk** [comment]
Thanks for the info! I just found LiveG earlier today by coming across the Twitter post showing off the branded back cover designs for the PinePhone. I just tried out the image in VirtualBox on my PC and it runs super smoothly, and I love the animations! The accessibility features seem really well thought out too.

With how responsive the PinePhone Pro is, I'm definitely excited to try it out there, and there is always desire for more release images for the PinePhones to play with so I do hope this gets official images for both phones as it seems like it would be very comfortable to use on mobile. You are right in that there aren't too many differences to work around between the phones, and the community has documented a lot of the differences quite well. Even if a fully custom build isn't feasible/sensible, I'm sure spinning an existing release like Mobian would be very welcome as well. Can't wait to see what happens with this beautiful interface! (Feel free to close this as an issue if it doesn't quite fit here)

**Comment by James-Livesey** [comment]
Ah thanks for checking it all out! There's plenty of stuff to be added, but I'd say I'm pretty pleased with what has been achieved with it all so far.

How have you found the PinePhone Pro so far? Last time I checked it looked like there was a bunch of software support for hardware such as cameras missing; not to mention the battery life which I think is a lot shorter compared to the PinePhone since it consumes a lot more power. From what I've seen, the PinePhone Pro would definitely be a good match for LiveG OS considering how smooth its experience is compared to the original PinePhone!

It'd definitely be great to get to an official 1.0 release of LiveG OS that people can actually _use_ daily to make calls, browse the internet etc. I find the trouble with Plasma Mobile and Phosh is that they integrate a lot of third-party software that doesn't always work well with the rest of the device! I'm sure the community is itching to get its hands on a new OS with a different design methodology to what's currently out there...

That being said I've always wanted to build a proper open-hardware smartphone that would complement the OS really well. It'd certainly be a long-term goal since it'd be an expensive one, but I might get round to it someday! Maybe something based on a [Radxa CM3](https://wiki.radxa.com/Rock3/CM/CM3) as the compute module and a [Quectel EG25-G](https://www.quectel.com/product/lte-eg25-g) for cellular comms — not to mention some sort of nice high-res display that can communicate over MIPI (though I think this might be the hardest part to integrate since there's a lot of software _and_ hardware work to get a smartphone display working properly I believe) along with some cameras and other parts. One day!

---

I'll go ahead and close off this issue and open a few more in other repos to remind me to update the website etc. Feel free to continue the discussion here though!
